menu = "y"
while menu == "y" :
    print("#-------------------------------------------#")
    print("#----------------LAPAK MURCE----------------#")
    print("#-------------------------------------------#")
    print("#  No    | Menu                             #")
    print("#-------------------------------------------#")
    print("#  1     | Buah                             #")
    print("#  2     | Sayur                            #")
    print("#  3     | Ubi-ubian                        #")

    pilih_menu = input("Silahkan Ketik Menu :")

    if pilih_menu == "buah":
        print("#-------------------------------------------#")
        print("#  No    | Nama Buah                        #")
        print("#-------------------------------------------#")
        print("#  1     | Appel                            #")
        print("#  2     | Anggur                           #")
        print("#  3     | Pear                             #")
        print("#  4     | Jeruk                            #")
        print("#  5     | Melon                            #")
        print("#-------------------------------------------#")

    elif pilih_menu == "sayur":
        print("#-------------------------------------------#")
        print("#  No    | Nama Sayur                       #")
        print("#-------------------------------------------#")
        print("#  1     | Sawi                             #")
        print("#  2     | Selada                           #")
        print("#  3     | Kangkung                         #")
        print("#  4     | Pakis                            #")
        print("#  5     | Kelor                            #")
        print("#-------------------------------------------#")
    elif pilih_menu == "ubi":
        print("#-------------------------------------------#")
        print("#  No    | Nama ubi                         #")
        print("#-------------------------------------------#")
        print("#  1     | Kentang                          #")
        print("#  2     | Sweet Potato                     #")
        print("#  3     | Ubi Ungu                         #")
        print("#  4     | Singkong                         #")
        print("#-------------------------------------------#")
    else:
        print("Menu Kosong")
        menu = input ("menu tidak tersedia")
    print("#-------------------------------------------#")
    pesan = input("Silahkan Pilih menu Pesanan Anda :")
    qty = input("Jumlah Pesanan: ")
    print("#-------------------------------------------#")
    print("Barang yang di pesan :")
    print("#-------------------------------------------#")
    pesanan = ()
    print(f"1.{pesan} | {qty} qyt" )
    menu = input("Apakah ada Tambahan? (y/n) ")
    print("#-------------------------------------------#")
    print("#          Pesanan Sedang di Proses         #")
    print("#           T E R I M A  K A S I H          #")
    print("#-------------------------------------------#")